config/routes.rb
Rails.application.routes.draw do
  root to: 'users#top'
  
  get    'signup', to: 'users#show'
  get    'login' , to: 'sessions#new'
  post   'login' , to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users
  resources :microposts
  resources :menus
  resources :recipes
  resources :quantities
  resources :relationships, only: [:create, :destroy]

  scope '(/:locale)', constraints: { locale: /\w{2}/ } do
    get '/intro', controller: :home, action: :intro
  end  

end

app/models/menu.rb
class Menu < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true
  validates :menu_name, presence: true
  validates :description, length: { maximum: 200 }
  has_many :recipes, dependent: :destroy
  
  def recipe?(menu_params)
    recipe.find_by(menu_params)
  end
  
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
end

app/models/microspost.rb
class Microspost < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
end

app/models/quantity.rb
class Quantity < ActiveRecord::Base
  validates :recipe_name, presence: true
  
  belongs_to :recipe    
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :menu, class_name: "Menu"
  has_many :quantity, dependent: :destroy    
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = self.email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  has_many :microposts
  has_many :menus, dependent: :destroy 
 
  has_many :following_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy 
  has_many :following_users, through: :following_relationships, source: :followed 

  has_many :follower_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy 
  has_many :follower_users, through: :follower_relationships, source: :follower 
 
  def follow(other_user)  
    following_relationships.find_or_create_by(followed_id: other_user_id)
  end
  
  def unfollow(other_user)
    following_relationship = following_relationships.find_by(followed_id: other_user_id)
    following_relationship.destroy if following_relationship
  end
  
  def following?(other_user)
    followning_users.includes(other_user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :set_locale

  private
  # I18n.locale をセットする
  def set_locale
    I18n.locale = locale_in_params || locale_in_accept_language || I18n.default_locale
  end

  # params の locale の値（優先すべき）
  # @return [Symbol]
  #   params から取った locale
  #   有効な値でなければ :ja
  #   取得できなかった場合 nil
  def locale_in_params
    if params[:locale].present?
      params[:locale].to_sym.presence_in(I18n::available_locales) || I18n.default_locale
    else
      nil
    end
  end

  # 環境変数 HTTP_ACCEPT_LANGUAGE を順に検証し、最初に一致した有効な locale を返す
  # @return [Symbol]  環境変数 HTTP_ACCEPT_LANGUAGE から取った locale 。取得できなかった場合 nil
  def locale_in_accept_language
    request.env['HTTP_ACCEPT_LANGUAGE']
      .to_s # nil 対策
      .split(',')
      .map{ |_| _[0..1].to_sym }
      .select { |_| I18n::available_locales.include?(_) }
      .first
  end

  # 全リンクに locale 情報をセットする
  # @return [Hash] locale をキーとするハッシュ
  def default_url_options(options = {})
    { locale: I18n.locale }
  end
  
  def logged_in_user
    root_path
    
    unless logged_in?
      store_location
      flash[:danger] = "Please log in."
      redirect_to login_url
    end  
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  def show
    @menu = Menu.find(params[:id])
    @user = @menu.user
    #redirect_to 'index'
    @recipes = @menu.recipes
    @recipe = Recipe.new
  end

  def index
    @user = current_user
  end

  def new
    @menu = current_user.menus.build
  end
  
  def create
    @menu = current_user.menus.build(menu_params)
    p @menu.inspect
    if @menu.save
      flash[:success] = "Saved successfully."
      redirect_to menus_path(@menu)
    else
      render 'new'
    end
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :email)
  end  
  
  def menu_params
    params.require(:menu).permit(:menu_date, :menu_name, :description)
  end

end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
    before_action :logged_in_user, only: [:create, :destroy]

  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "Micropost created!"
      redirect_to root_url
    else
      render 'static_pages/home'
    end
  end
  
  def destroy
    @micropost = current_user.microposts.find_by(id: params[:id])
    return redirect_to root_url if @micropost.nil?
    @micropost.destroy
    flash[:success] = "Micropost deleted"
    redirect_to request.referrer || root_url
  end
  
  private
  def micropost_params
    params.require(:micropost).permit(:content)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action: logged_in_user
  def create
    @user = User.find(params[:followed_id])
    current_user.follow(@user)
  end

  def destroy
    @user = current_user.following_relationships.find(params[:id]).followed
    current_user.unfollow(@user)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      flash[:info] = "logged in as #{@user.name}"
      redirect_to @user
    else
      flash[:danger] = 'invalid email/password combination'
      render 'new'
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def top
  end
  
  def show 
    @user = User.find(params[:id])
    @microposts = @user.microposts.order(created_at: :desc)
  end
  
  #def home
  #  @micropost = current_user.microposts.build if logged_in?
  #end

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the Remin-De-Recipe!"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) 
  end
  
  def logged_in?
    !!current_user 
  end
  
  def store_location
      session[:forwarding_url] = request.url if request.get?
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
  <h1 class="project_title"><%= link_to t('.project_name'), '#' %></h1>
  <nav>
      <ul class="nav navbar-nav navbar-left">
        <li ><%#= link_to t('.home'), root_path %></li>
  
<% if logged_in? %>
      <li ><%= link_to t('.myrecipe'), menus_path %></li>
      <li ><%= link_to t('.myfavorite'), '#' %></li>
      <li ><%= link_to t('.myprofile'), '#' %></li>
<% else %>
        <li ><%= link_to t('.sign_up'), new_user_path %></li>
        <li ><%= link_to t('.login'), login_path %></li>
<% end %>

      </ul>
  

      <!-- Small button group -->
      <ul class="nav navbar-nav navbar-right" style="width: 350px; ">

<% if logged_in? %>
      <li style="color:#ffffff;"> 
      <strong><%= t('.hello') %></strong> <%= current_user.name %>
      </li>
      <span style="margin-right: 10em;"></span>
      <li style="text-align:right;"> <%= link_to t('.logout'), logout_path, method: "delete"%> </li>
<% end %>       
      <div class="btn-group"> 
        <button class="btn btn-default btn-sm dropdown-toggle navbar-right" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="width: 110px;">
          <%= t('.language') %> <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
          <li><%= link_to( t('.english'), url_for(params.merge(locale: 'en'))) %></li>
          <li><%= link_to( t('.japanese'), url_for(params.merge(locale: 'ja'))) %></li>
        </ul>
      </div>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_header.html.haml
%ul.dropdown-menu{role: 'menu'}
  :ruby
    locales = {
      ja: '日本語',
      en: 'English',
    }
  - locales.each do |locale, label|
    - label = (I18n.locale == locale ? icon('check') : '') + label
    %li= link_to(label, url_for(params.merge(locale: locale)))

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Remin-DE-Recipe</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body style="padding: 180px;">

  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |message_type, message| %> 
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %> 
    
    <%= yield %>
  </div>

</body>
</html>

app/views/menus/_sidemenu.html.erb
<div class="col-sm-3">
<%#= link_to "テストレシピ new", new_menu_path if current_user %>    
  <div class="sidebar-module sidebar-module-inset">
    <%= link_to t('.new_recipe'), new_menu_path, class: "btn btn-large btn-success" %>
  </div>
</div>    

app/views/menus/index.html.erb
<div class="container">
  <h1>
    <%= @user.name +  t('.your_recipe') %>
  </h1>

  <div class="container">
   <div class= "col-sm-9">
   
    <div class="row">
    <% @user.menus.each do |menu| %>
      <div class="col-sm-3" style="text-align: center">
        <h2><%= menu.menu_name %></h2>
        <p><img class="img-circle" src="" alt="" width="160" height="160">
        </p>
        <p><%= menu.description %></p>
        <%= link_to t('.view_details'), menu %>    
      </div>
    <% end %>
    </div>      
  </div>      
  <%= render 'menus/sidemenu' %>
    
  </div>
</div>

app/views/menus/new.html.erb
<h1><%= t('.title_menu') %></h1>


<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@menu) do |f| %>
      
      <%= render 'shared/error_messages', object: f.object %>
      
      <%= f.label t('.menu_name') %>
      <%= f.text_field :menu_name %>
      
      <%= f.label t('.menu_date') %>
      <%= f.date_field :menu_date %>
      
      <%= f.label t('.description') %>
      <%= f.text_area :description %>
      
      <%= f.submit t('.create_menu'), class: "btn btn-large btn-primary" %>
    <% end %>
  </div>

</div>


  <!--create_table "menus", force: :cascade do |t|-->
  <!--  t.integer  "user_id"-->
  <!--  t.date     "menu_date"-->
  <!--  t.string   "menu_name"-->
  <!--  t.string   "description"-->
  <!--  t.datetime "created_at",  null: false-->
  <!--  t.datetime "updated_at",  null: false-->
  <!--end-->

app/views/menus/show.html.erb
<div class="container">
  <h1>
    <%= @user.name +  t('.your_recipe') %>
  </h1>

  <div class="container">
    <div class="row">
      <div class="col-sm-3" style="text-align: center">
        <h2>title</h2>
        <p><img class="img-circle" src="" alt="" width="180" height="180">
        </p>
        <o>aaaa</o>
        <%= link_to t('.view_details') %>    
      </div>

  <%= render 'menus/sidemenu' %>
      
    
    </div>  
  </div>
</div>

<%# @recipes.each do |f| %>
  <%#= form_for(f) do |fx| %>
    <%#= fx.text_field "材料と分量のカラムがない", readonly: true %>
    <%#= fx.text_field "材料と分量のカラムがない", readonly: true %>
  <%# end %>
<%# end %>

<%= form_for(@recipe) do |f| %>
  <%= f.text_field "材料と分量のカラムがない" %>
  <%= f.text_field "材料と分量のカラムがない" %>
  <%= f.submit %>
<% end %>

app/views/microposts/_microsopost.html.erb
<li id="micropost-<%= micropost.id %>">
  <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class="content"><%= micropost.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
    <% if current_user == micropost.user %>
      <%= link_to "delete", micropost, method: :delete,
                                       data: { confirm: "You sure?" } %>
    <% end %>
  </span>
</li>

app/views/relationships/create.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/unfollow')) %>");

app/views/relationships/destroy.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/follow')) %>");

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% if current_user != @user %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_top_login.html.erb
<ul>
  <% Menu.all.each do |menu| %>
    <li><%= menu.menu_name %></li>
  <% end %>
</ul>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/new.html.erb
<h1><%= t('.title_signup') %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      
      <%= render 'shared/error_messages', object: f.object %> 
      
      <%= f.label t('.name') %>
      <%= f.text_field :name, class: 'form-control',  :placeholder => t('.sample_name') %>

      <%= f.label t('.email') %>
      <%= f.text_field :email, class: 'form-control',  :placeholder => t('.sample_email') %>

      <%= f.label t('.password') %>
      <%= f.password_field :password, class: 'form-control',  :placeholder => t('.sample_password') %>

      <%= f.label t('.password_confirmation')  %>
      <%= f.password_field :password_confirmation, class: 'form-control',  :placeholder => t('.sample_password') %>

      <%= f.submit t('.create_my_account'), class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
    <div class="row">
      <aside class="col-md-5">
        <section class="user_info">
          <h1>
            <%= gravatar_for @user %>
            <%= @user.name + t('.your_profile') %>
          </h1>
          <p>プロフィールなど追加？</p>
        </section>
      </aside>
    <div class="col-md-5">
      <%#= render 'follow_form' if logged_in? %>
      <% if @user.microposts.any? %>
      <h3>Microposts (<%= @user.microposts.count %>)</h3>
      <ol class="microposts">
        <%= render @microposts %>
      </ol>
      <% end %>
    </div>
   </div>
</div>

app/views/users/top.html.erb
<div class="container">
  <% if current_user %>
    <%= render 'top_login' %>
  <% else %>
    <div class="center jumbotron">
      <h1><%= t('.welcome_msg') %></h1>
      <%= link_to t('.sign_up_now'), signup_path, class: "btn btn-lg btn-primary" %>
    </div>
  <% end %>
</div>